import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, query, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { firebaseSettings } from './firebase-settings.js';

const app = initializeApp(firebaseSettings);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');

const ACTIVE = ['Active', 'Training', 'On Leave'];
const statuses = ['Active', 'Training', 'On Leave', 'Suspended', 'Resigned', 'Terminated', 'Archived'];
const taskStatuses = ['Not Started', 'In Progress', 'Waiting Review', 'Completed', 'Rejected'];
const ticketStatuses = ['Open', 'Under Review', 'Waiting Response', 'Resolved', 'Closed'];
const priorities = ['Low', 'Normal', 'High', 'Critical'];
const ranks = [['Founder / Chief Executive Officer',8,'Ownership'],['Chief Operating Officer',7,'Executive'],['Chief Compliance Officer',7,'Executive'],['Department Director',6,'Department Leadership'],['Deputy Director',6,'Department Leadership'],['Division Manager',5,'Management'],['Supervisor',4,'Supervision'],['Senior Specialist',3,'Senior Staff'],['Specialist',2,'Staff'],['Associate',2,'Staff'],['Trainee',1,'Trainee']];
const departments = ['Executive Office','Human Resources','Accreditation Services','Records & Intelligence','Investigations','Operations','Technology','Public Relations'];
const state = { user:null, employee:null, page:'dashboard', employees:[], tasks:[], tickets:[], audits:[], notice:'' };

const norm = v => String(v || '').trim().toLowerCase();
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val = id => document.querySelector(id)?.value || '';
const can = n => Number(state.employee?.accessLevel || 0) >= n;
const today = () => new Date().toISOString().slice(0,10);
const rankByTitle = t => ranks.find(r => r[0] === t) || ranks.at(-1);
const employeeName = id => state.employees.find(e => e.employeeId === id)?.discordUsername || id || 'Unassigned';
function badge(v){const t=esc(v||'Unknown');const c=/active|completed|resolved|linked/i.test(t)?'green':/training|review|waiting|progress|leave|open/i.test(t)?'yellow':/suspend|terminated|rejected|closed|critical/i.test(t)?'red':'blue';return `<span class="badge ${c}">${t}</span>`;}
async function session(){if(auth.currentUser)return auth.currentUser;return (await signInAnonymously(auth)).user;}
async function audit(action,details={}){try{await addDoc(collection(db,'auditLogs'),{action,details,actorUid:state.user?.uid||'system',actorEmployeeId:state.employee?.employeeId||'SYSTEM',actorDiscordUsername:state.employee?.discordUsername||'System',createdAt:serverTimestamp()});}catch{}}
async function run(fn,msg){try{await fn();state.notice=msg;await loadAll();renderPortal();}catch(e){state.notice=`Action failed: ${e.message}`;renderPortal();}}

async function init(){try{root.innerHTML=`<section class="boot-screen"><div><div class="brand-mark">CS</div><h1>Cognitus Solutions</h1><p>Opening staff portal...</p></div></section>`;state.user=await session();const saved=localStorage.getItem('cognitusEmployeeId');if(saved){const s=await getDoc(doc(db,'employees',saved));if(s.exists()&&s.data().authUid===state.user.uid&&ACTIVE.includes(s.data().status)){state.employee=s.data();await loadAll();return renderPortal();}}renderLogin();}catch(e){renderError(e);}}
function renderError(e){root.innerHTML=`<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Cognitus Solutions</h1><p>Staff Portal</p></div></div><div class="notice error"><strong>Setup issue.</strong><br>${esc(e.message)}</div><p class="muted">Check Firebase settings, enable Anonymous Authentication, enable Firestore, and deploy Firestore rules.</p></div></section>`;}
function renderLogin(message=''){root.innerHTML=`<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Cognitus Solutions</h1><p>Employee Operations Portal</p></div></div>${message?`<div class="notice">${esc(message)}</div>`:''}<div class="notice warn"><strong>Authorized staff only.</strong><br>Enter your assigned Discord Username and Employee ID. No default credentials are displayed.</div><form id="loginForm" class="form-grid"><label>Discord Username<input id="discordUsername" autocomplete="username" placeholder="Enter your Discord username" required></label><label>Employee ID<input id="employeeId" autocomplete="off" placeholder="Enter your Employee ID" required></label><button class="primary-btn">Enter Staff Portal</button></form><p class="muted">Need access? Contact Cognitus leadership for an employee record.</p></div></section>`;document.querySelector('#loginForm').addEventListener('submit',login);}
async function login(e){e.preventDefault();try{state.user=await session();const username=norm(val('#discordUsername'));const employeeId=val('#employeeId').trim();const ref=doc(db,'employees',employeeId);const s=await getDoc(ref);if(!s.exists())return renderLogin('No employee record was found for that Employee ID.');const emp=s.data();if(norm(emp.discordUsername)!==username)return renderLogin('The Discord Username does not match that Employee ID.');if(!ACTIVE.includes(emp.status))return renderLogin('This employee account is not currently active.');if(emp.authUid&&emp.authUid!==state.user.uid)return renderLogin('This employee record is already linked. Leadership can reset the link from Employee Management.');if(!emp.authUid)await updateDoc(ref,{authUid:state.user.uid,updatedAt:serverTimestamp()});state.employee={...emp,authUid:state.user.uid};localStorage.setItem('cognitusEmployeeId',employeeId);await audit('EMPLOYEE_LOGIN',{employeeId});await loadAll();state.notice='Welcome back.';renderPortal();}catch(e){renderLogin(`Login failed: ${e.message}`);}}
async function loadAll(){state.employees=(await getDocs(query(collection(db,'employees'),orderBy('employeeId'),limit(300)))).docs.map(d=>({id:d.id,...d.data()}));state.tasks=(await getDocs(query(collection(db,'tasks'),orderBy('createdAt','desc'),limit(250)))).docs.map(d=>({id:d.id,...d.data()}));state.tickets=(await getDocs(query(collection(db,'tickets'),orderBy('createdAt','desc'),limit(250)))).docs.map(d=>({id:d.id,...d.data()}));state.audits=can(7)?(await getDocs(query(collection(db,'auditLogs'),orderBy('createdAt','desc'),limit(150)))).docs.map(d=>({id:d.id,...d.data()})):[];}
function visibleTasks(){return can(5)?state.tasks:state.tasks.filter(t=>t.assignedToEmployeeId===state.employee.employeeId||t.createdByEmployeeId===state.employee.employeeId);}function visibleTickets(){return can(6)?state.tickets:state.tickets.filter(t=>t.createdByEmployeeId===state.employee.employeeId||t.assignedToEmployeeId===state.employee.employeeId);}function navItems(){return [['dashboard','Dashboard',1],['directory','Directory',2],['tasks','Tasks',2],['tickets','Tickets',1],['employees','Employees',6],['audits','Audit Logs',7],['ranks','Ranks',1],['setup','Setup',7]].filter(i=>can(i[2]));}
function renderPortal(){const n=state.notice;state.notice='';root.innerHTML=`<div class="portal-layout"><aside class="sidebar"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Cognitus</h1><p>Staff Portal</p></div></div><nav class="nav-list">${navItems().map(([k,l])=>`<button class="nav-btn ${state.page===k?'active':''}" data-page="${k}">${l}</button>`).join('')}</nav><div class="sidebar-footer"><button id="logoutBtn" class="ghost-btn" style="width:100%">Sign Out</button></div></aside><main class="main"><div class="portal-topbar"><div><h2>${title()}</h2><p class="muted">${esc(state.employee.discordUsername)} • ${esc(state.employee.employeeId)} • ${esc(state.employee.rank)}</p></div><div class="topbar-actions">${badge(state.employee.status)}${badge('Level '+state.employee.accessLevel)}</div></div>${n?`<div class="notice ${n.startsWith('Action failed')?'error':'success'}">${esc(n)}</div>`:''}<section>${page()}</section></main></div>`;document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',async()=>{state.page=b.dataset.page;await loadAll();renderPortal();}));document.querySelector('#logoutBtn').addEventListener('click',()=>{localStorage.removeItem('cognitusEmployeeId');state.employee=null;state.page='dashboard';renderLogin('You have signed out on this browser.');});wire();}
function title(){return({dashboard:'Command Dashboard',directory:'Employee Directory',tasks:'Task Center',tickets:'Internal Tickets',employees:'Manage Employees',audits:'Audit Logs',ranks:'Rank Structure',setup:'System Setup'})[state.page]||'Staff Portal';}function page(){return state.page==='directory'?directory():state.page==='tasks'?tasks():state.page==='tickets'?tickets():state.page==='employees'?employees():state.page==='audits'?audits():state.page==='ranks'?ranksPage():state.page==='setup'?setup():dashboard();}
function dashboard(){const active=state.employees.filter(e=>e.status==='Active').length;const openTasks=visibleTasks().filter(t=>t.status!=='Completed').length;const openTickets=visibleTickets().filter(t=>!['Resolved','Closed'].includes(t.status)).length;return `<div class="grid four"><div class="stat-card"><p>Active Employees</p><strong>${active}</strong></div><div class="stat-card"><p>Visible Tasks</p><strong>${visibleTasks().length}</strong></div><div class="stat-card"><p>Open Tasks</p><strong>${openTasks}</strong></div><div class="stat-card"><p>Open Tickets</p><strong>${openTickets}</strong></div></div><div class="grid two" style="margin-top:1rem"><section class="card"><h3>Your Profile</h3>${profile(state.employee)}</section><section class="card"><h3>Quick Actions</h3><div class="action-row"><button class="secondary-btn" data-jump="tasks">View Tasks</button><button class="secondary-btn" data-jump="tickets">Open Ticket</button>${can(6)?'<button class="secondary-btn" data-jump="employees">Add Employee</button>':''}</div><hr><p class="muted">Use this portal for employee records, tasks, internal tickets, documentation, and audit-ready operations.</p></section></div><section class="card" style="margin-top:1rem"><h3>Recent Tasks</h3>${taskTable(visibleTasks().slice(0,5))}</section>`;}
function profile(e){return `<div class="table-wrap"><table><tbody><tr><th>Employee ID</th><td>${esc(e.employeeId)}</td></tr><tr><th>Discord</th><td>${esc(e.discordUsername)}</td></tr><tr><th>Department</th><td>${esc(e.department)}</td></tr><tr><th>Rank</th><td>${esc(e.rank)}</td></tr><tr><th>Status</th><td>${badge(e.status)}</td></tr><tr><th>Auth Link</th><td>${e.authUid?badge('Linked'):badge('Open')}</td></tr></tbody></table></div>`;}
function employeeRows(rows,manage=false){if(!rows.length)return '<div class="empty-state">No employees found.</div>';return `<div class="table-wrap"><table><thead><tr><th>ID</th><th>Discord</th><th>Department</th><th>Rank</th><th>Status</th><th>Auth</th>${manage?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(e=>`<tr><td>${esc(e.employeeId)}</td><td>${esc(e.discordUsername)}</td><td>${esc(e.department)}</td><td>${esc(e.rank)}</td><td>${badge(e.status)}</td><td>${e.authUid?badge('Linked'):badge('Open')}</td>${manage?`<td><div class="action-row"><select data-emp-status="${esc(e.employeeId)}">${statuses.map(s=>`<option ${e.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="small-btn" data-reset-auth="${esc(e.employeeId)}">Reset Link</button></div></td>`:''}</tr>`).join('')}</tbody></table></div>`;}
function directory(){return `<div class="card"><div class="toolbar"><input id="employeeSearch" placeholder="Search employees..."><button class="secondary-btn" data-refresh>Refresh</button></div><h3>Employees</h3>${employeeRows(state.employees)}</div>`;}function tasks(){return `<div class="grid two"><section class="card"><h3>Create Task</h3>${can(4)?taskForm():'<p class="muted">Supervisors and above can create tasks.</p>'}</section><section class="card"><h3>Task Queue</h3>${taskTable(visibleTasks())}</section></div>`;}function taskForm(){return `<form id="taskForm" class="form-grid"><label>Title<input id="taskTitle" required></label><label>Assign To<select id="taskAssignedTo">${state.employees.filter(e=>ACTIVE.includes(e.status)).map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)} (${esc(e.employeeId)})</option>`).join('')}</select></label><label>Priority<select id="taskPriority">${priorities.map(p=>`<option ${p==='Normal'?'selected':''}>${p}</option>`).join('')}</select></label><label>Due Date<input id="taskDue" type="date"></label><label>Description<textarea id="taskDescription"></textarea></label><button class="primary-btn">Create Task</button></form>`;}function taskTable(rows){if(!rows.length)return '<div class="empty-state">No visible tasks yet.</div>';return `<div class="table-wrap"><table><thead><tr><th>Task</th><th>Assigned</th><th>Priority</th><th>Status</th><th>Update</th></tr></thead><tbody>${rows.map(t=>`<tr><td><strong>${esc(t.title)}</strong><br><span class="muted">${esc(t.description||'No description')}</span></td><td>${esc(employeeName(t.assignedToEmployeeId))}</td><td>${badge(t.priority||'Normal')}</td><td>${badge(t.status)}</td><td><select data-task-status="${t.id}">${taskStatuses.map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`;}
function tickets(){return `<div class="grid two"><section class="card"><h3>Open Internal Ticket</h3><form id="ticketForm" class="form-grid"><label>Category<select id="ticketCategory"><option>Human Resources</option><option>Technology</option><option>Operations</option><option>Management Review</option><option>Other</option></select></label><label>Subject<input id="ticketSubject" required></label><label>Details<textarea id="ticketDetails" required></textarea></label><button class="primary-btn">Submit Ticket</button></form></section><section class="card"><h3>Ticket Queue</h3>${ticketRows(visibleTickets())}</section></div>`;}function ticketRows(rows){if(!rows.length)return '<div class="empty-state">No visible tickets yet.</div>';return `<div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Created By</th><th>Status</th><th>Update</th></tr></thead><tbody>${rows.map(t=>`<tr><td><strong>${esc(t.subject)}</strong><br><span class="muted">${esc(t.category)} — ${esc(t.details||'')}</span></td><td>${esc(employeeName(t.createdByEmployeeId))}</td><td>${badge(t.status)}</td><td>${can(6)||t.createdByEmployeeId===state.employee.employeeId?`<select data-ticket-status="${t.id}">${ticketStatuses.map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select>`:'—'}</td></tr>`).join('')}</tbody></table></div>`;}
function employees(){return `<div class="grid two"><section class="card"><h3>Create Employee</h3><form id="employeeForm" class="form-grid"><label>Employee ID<input id="newEmployeeId" placeholder="Example: COG-DEPT-001" required></label><label>Discord Username<input id="newDiscordUsername" placeholder="Employee Discord username" required></label><label>Display Name<input id="newDisplayName"></label><label>Discord User ID Optional<input id="newDiscordUserId"></label><label>Department<select id="newDepartment">${departments.map(d=>`<option>${d}</option>`).join('')}</select></label><label>Rank<select id="newRank">${ranks.map(r=>`<option>${r[0]}</option>`).join('')}</select></label><label>Status<select id="newStatus">${statuses.map(s=>`<option>${s}</option>`).join('')}</select></label><button class="primary-btn">Create Employee</button></form></section><section class="card"><h3>Employee Records</h3>${employeeRows(state.employees,true)}</section></div>`;}function audits(){return `<div class="card"><h3>Recent Audit Logs</h3>${state.audits.length?`<div class="table-wrap"><table><thead><tr><th>Action</th><th>Actor</th><th>Details</th></tr></thead><tbody>${state.audits.map(a=>`<tr><td>${esc(a.action)}</td><td>${esc(a.actorDiscordUsername)}<br><span class="muted">${esc(a.actorEmployeeId)}</span></td><td><code>${esc(JSON.stringify(a.details||{}))}</code></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No audit logs found.</div>'}</div>`;}function ranksPage(){return `<div class="grid two"><section class="card"><h3>Rank Structure</h3><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Group</th><th>Access</th></tr></thead><tbody>${ranks.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[2])}</td><td>${badge('Level '+r[1])}</td></tr>`).join('')}</tbody></table></div></section><section class="card"><h3>Departments</h3><div class="table-wrap"><table><tbody>${departments.map(d=>`<tr><td>${esc(d)}</td></tr>`).join('')}</tbody></table></div></section></div>`;}function setup(){return `<div class="grid two"><section class="card"><h3>Production Checklist</h3><p>${badge('Firestore')} ${badge('Anonymous Auth')} ${badge('Rules')} ${badge('Hosting')}</p><hr><p class="muted">After every rules or hosting change, deploy Firebase and hard refresh the browser.</p></section><section class="card"><h3>Staff Onboarding</h3><p class="muted">Create an employee record, give the employee their exact Discord Username and Employee ID, then have them log in from their own browser. Use Reset Link if they change devices or clear browser data.</p></section></div>`;}
function wire(){document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',async()=>{state.page=b.dataset.jump;await loadAll();renderPortal();}));document.querySelectorAll('[data-refresh]').forEach(b=>b.addEventListener('click',async()=>{await loadAll();state.notice='Refreshed.';renderPortal();}));document.querySelector('#employeeSearch')?.addEventListener('input',e=>{const term=norm(e.target.value);const rows=term?state.employees.filter(x=>norm(`${x.employeeId} ${x.discordUsername} ${x.department} ${x.rank} ${x.status}`).includes(term)):state.employees;e.target.closest('.card').querySelector('.table-wrap,.empty-state').outerHTML=employeeRows(rows,state.page==='employees');wire();});document.querySelector('#taskForm')?.addEventListener('submit',createTask);document.querySelector('#ticketForm')?.addEventListener('submit',createTicket);document.querySelector('#employeeForm')?.addEventListener('submit',createEmployee);document.querySelectorAll('[data-task-status]').forEach(x=>x.addEventListener('change',()=>run(async()=>{await updateDoc(doc(db,'tasks',x.dataset.taskStatus),{status:x.value,updatedAt:serverTimestamp(),updatedByEmployeeId:state.employee.employeeId});await audit('TASK_STATUS_UPDATED',{taskId:x.dataset.taskStatus,status:x.value});},'Task status updated.')));document.querySelectorAll('[data-ticket-status]').forEach(x=>x.addEventListener('change',()=>run(async()=>{await updateDoc(doc(db,'tickets',x.dataset.ticketStatus),{status:x.value,updatedAt:serverTimestamp(),updatedByEmployeeId:state.employee.employeeId});await audit('TICKET_STATUS_UPDATED',{ticketId:x.dataset.ticketStatus,status:x.value});},'Ticket status updated.')));document.querySelectorAll('[data-emp-status]').forEach(x=>x.addEventListener('change',()=>run(async()=>{await updateDoc(doc(db,'employees',x.dataset.empStatus),{status:x.value,updatedAt:serverTimestamp(),updatedByEmployeeId:state.employee.employeeId});await audit('EMPLOYEE_STATUS_UPDATED',{employeeId:x.dataset.empStatus,status:x.value});},'Employee status updated.')));document.querySelectorAll('[data-reset-auth]').forEach(x=>x.addEventListener('click',()=>run(async()=>{await updateDoc(doc(db,'employees',x.dataset.resetAuth),{authUid:null,updatedAt:serverTimestamp(),updatedByEmployeeId:state.employee.employeeId});await audit('EMPLOYEE_AUTH_RESET',{employeeId:x.dataset.resetAuth});},'Employee login link reset.')));}
async function createTask(e){e.preventDefault();await run(async()=>{const assignedTo=val('#taskAssignedTo');await addDoc(collection(db,'tasks'),{title:val('#taskTitle').trim(),assignedToEmployeeId:assignedTo,priority:val('#taskPriority'),dueDate:val('#taskDue')||null,description:val('#taskDescription').trim(),status:'Not Started',createdByEmployeeId:state.employee.employeeId,updatedByEmployeeId:state.employee.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit('TASK_CREATED',{assignedTo});},'Task created.');}async function createTicket(e){e.preventDefault();await run(async()=>{await addDoc(collection(db,'tickets'),{category:val('#ticketCategory'),subject:val('#ticketSubject').trim(),details:val('#ticketDetails').trim(),status:'Open',createdByEmployeeId:state.employee.employeeId,updatedByEmployeeId:state.employee.employeeId,assignedToEmployeeId:null,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit('TICKET_CREATED',{category:val('#ticketCategory')});},'Ticket submitted.');}async function createEmployee(e){e.preventDefault();await run(async()=>{const employeeId=val('#newEmployeeId').trim();const discordUsername=val('#newDiscordUsername').trim();const rank=rankByTitle(val('#newRank'));if((await getDoc(doc(db,'employees',employeeId))).exists())throw new Error('That Employee ID already exists.');await setDoc(doc(db,'employees',employeeId),{employeeId,discordUsername,discordUsernameLower:norm(discordUsername),discordUserId:val('#newDiscordUserId').trim(),authUid:null,displayName:val('#newDisplayName').trim()||discordUsername,rank:rank[0],rankGroup:rank[2],department:val('#newDepartment'),accessLevel:rank[1],status:val('#newStatus'),supervisorId:state.employee.employeeId,hireDate:today(),createdBy:state.employee.employeeId,updatedByEmployeeId:state.employee.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit('EMPLOYEE_CREATED',{employeeId,discordUsername,rank:rank[0]});},'Employee created.');}

init();
