import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, query, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { firebaseSettings } from './firebase-settings.js';

const app=initializeApp(firebaseSettings), auth=getAuth(app), db=getFirestore(app), root=document.querySelector('#app');
const ACTIVE=['Active','Training','On Leave'], statuses=['Active','Training','On Leave','Suspended','Resigned','Terminated','Archived'];
const taskStatuses=['Not Started','In Progress','Waiting Review','Completed','Rejected'], ticketStatuses=['Open','Under Review','Waiting Response','Resolved','Closed'];
const caseStatuses=['Open','Intake Review','Assigned','Investigating','Pending Decision','Actioned','Closed','Reopened'];
const caseTypes=['Conduct','Harassment','Policy Violation','Fraud/Assets','Security/Access','Authority Boundaries','Other'];
const accessLevels=[0,1,2,3,4,5,6,7,8];
const ranks=[['Founder / Chief Executive Officer',8,'Ownership'],['Chief Operating Officer',7,'Executive'],['Chief Compliance Officer',7,'Executive'],['Department Director',6,'Department Leadership'],['Deputy Director',6,'Department Leadership'],['Division Manager',5,'Management'],['Supervisor',4,'Supervision'],['Senior Specialist',3,'Senior Staff'],['Specialist',2,'Staff'],['Associate',2,'Staff'],['Trainee',1,'Trainee']];
const departments=['Executive Office','Human Resources','Accreditation Services','Records & Intelligence','Investigations','Operations','Technology','Public Relations','Internal Affairs'];
let S={user:null,emp:null,page:'dashboard',employees:[],tasks:[],tickets:[],cases:[],audits:[],notice:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').trim().toLowerCase(), val=id=>document.querySelector(id)?.value||'', can=n=>Number(S.emp?.accessLevel||0)>=n, today=()=>new Date().toISOString().slice(0,10);
const sessions=e=>new Set([e?.authUid,...(Array.isArray(e?.authUids)?e.authUids:[])].filter(Boolean));
const hasSession=e=>sessions(e).has(S.user?.uid), empName=id=>S.employees.find(e=>e.employeeId===id)?.discordUsername||id||'Unassigned';
function badge(v){return `<span class="badge blue">${esc(v)}</span>`}
async function anon(){if(auth.currentUser)return auth.currentUser;return (await signInAnonymously(auth)).user}
async function log(action,details={}){try{await addDoc(collection(db,'auditLogs'),{action,details,actorUid:S.user?.uid||'system',actorEmployeeId:S.emp?.employeeId||'SYSTEM',actorDiscordUsername:S.emp?.discordUsername||'System',createdAt:serverTimestamp()})}catch{}}
async function load(){S.employees=(await getDocs(query(collection(db,'employees'),orderBy('employeeId'),limit(400)))).docs.map(d=>({id:d.id,...d.data()}));S.tasks=(await getDocs(query(collection(db,'tasks'),orderBy('createdAt','desc'),limit(250)))).docs.map(d=>({id:d.id,...d.data()}));S.tickets=(await getDocs(query(collection(db,'tickets'),orderBy('createdAt','desc'),limit(250)))).docs.map(d=>({id:d.id,...d.data()}));S.cases=(await getDocs(query(collection(db,'iaCases'),orderBy('createdAt','desc'),limit(250)))).docs.map(d=>({id:d.id,...d.data()}));S.audits=can(7)?(await getDocs(query(collection(db,'auditLogs'),orderBy('createdAt','desc'),limit(150)))).docs.map(d=>({id:d.id,...d.data()})):[]}
async function run(fn,msg){try{await fn();S.notice=msg;await load();render()}catch(e){S.notice='Action failed: '+e.message;render()}}
async function init(){try{root.innerHTML='<section class="boot-screen"><div><div class="brand-mark">CS</div><h1>Cognitus Solutions</h1><p>Opening staff portal...</p></div></section>';S.user=await anon();let saved=localStorage.getItem('cognitusEmployeeId');if(saved){let s=await getDoc(doc(db,'employees',saved));if(s.exists()&&hasSession(s.data())&&ACTIVE.includes(s.data().status)){S.emp=s.data();await load();return render()}}loginPage()}catch(e){root.innerHTML=`<section class="login-page"><div class="login-card"><h1>Setup issue</h1><div class="notice error">${esc(e.message)}</div></div></section>`}}
function loginPage(msg=''){root.innerHTML=`<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Cognitus Solutions</h1><p>Employee Operations Portal</p></div></div>${msg?`<div class="notice">${esc(msg)}</div>`:''}<div class="notice warn"><strong>Authorized staff only.</strong><br>Use your assigned Discord Username and Employee ID. Multiple browser/device logins are supported.</div><form id="loginForm" class="form-grid"><label>Discord Username<input id="u" placeholder="Enter your Discord username" required></label><label>Employee ID<input id="id" placeholder="Enter your Employee ID" required></label><button class="primary-btn">Enter Staff Portal</button></form></div></section>`;document.querySelector('#loginForm').addEventListener('submit',doLogin)}
async function doLogin(e){e.preventDefault();try{S.user=await anon();let employeeId=val('#id').trim(), username=norm(val('#u')), ref=doc(db,'employees',employeeId), snap=await getDoc(ref);if(!snap.exists())return loginPage('No employee record was found.');let emp=snap.data();if(norm(emp.discordUsername)!==username)return loginPage('The Discord Username does not match that Employee ID.');if(!ACTIVE.includes(emp.status))return loginPage('This employee account is not active.');let ids=[...sessions(emp),S.user.uid];let updates={authUids:[...new Set(ids)],lastLoginAt:serverTimestamp(),updatedAt:serverTimestamp()};if(!emp.authUid)updates.authUid=S.user.uid;await updateDoc(ref,updates);S.emp=(await getDoc(ref)).data();localStorage.setItem('cognitusEmployeeId',employeeId);await log('EMPLOYEE_LOGIN',{employeeId,multiDevice:true});await load();S.notice='Welcome back.';render()}catch(e){loginPage('Login failed: '+e.message)}}
function visibleTasks(){return can(5)?S.tasks:S.tasks.filter(t=>t.assignedToEmployeeId===S.emp.employeeId||t.createdByEmployeeId===S.emp.employeeId)}
function visibleTickets(){return can(6)?S.tickets:S.tickets.filter(t=>t.createdByEmployeeId===S.emp.employeeId||t.assignedToEmployeeId===S.emp.employeeId)}
function visibleCases(){return can(4)?S.cases:S.cases.filter(c=>c.createdByEmployeeId===S.emp.employeeId||c.assignedToEmployeeId===S.emp.employeeId)}
function nav(){return [['dashboard','Dashboard',1],['directory','Directory',2],['tasks','Tasks',2],['tickets','Tickets',1],['ia','Internal Affairs',4],['employees','Employees',6],['audits','Audit Logs',7],['ranks','Ranks',1],['setup','Setup',7]].filter(x=>can(x[2]))}
function render(){let n=S.notice;S.notice='';root.innerHTML=`<div class="portal-layout"><aside class="sidebar"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Cognitus</h1><p>Staff Portal</p></div></div><nav class="nav-list">${nav().map(([k,l])=>`<button class="nav-btn ${S.page===k?'active':''}" data-page="${k}">${l}</button>`).join('')}</nav><div class="sidebar-footer"><button id="out" class="ghost-btn" style="width:100%">Sign Out</button></div></aside><main class="main"><div class="portal-topbar"><div><h2>${title()}</h2><p class="muted">${esc(S.emp.discordUsername)} • ${esc(S.emp.employeeId)} • ${esc(S.emp.rank)}</p></div><div class="topbar-actions">${badge(S.emp.status)}${badge('Level '+S.emp.accessLevel)}${badge(sessions(S.emp).size+' sessions')}</div></div>${n?`<div class="notice ${n.startsWith('Action failed')?'error':'success'}">${esc(n)}</div>`:''}${page()}</main></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=async()=>{S.page=b.dataset.page;await load();render()});document.querySelector('#out').onclick=()=>{localStorage.removeItem('cognitusEmployeeId');S.emp=null;S.page='dashboard';loginPage('You have signed out on this browser.')};wire()}
function title(){return {dashboard:'Command Dashboard',directory:'Employee Directory',tasks:'Task Center',tickets:'Internal Tickets',ia:'Internal Affairs',employees:'Manage Employees',audits:'Audit Logs',ranks:'Rank Structure',setup:'System Setup'}[S.page]||'Portal'}
function page(){return S.page==='directory'?directory():S.page==='tasks'?tasks():S.page==='tickets'?tickets():S.page==='ia'?ia():S.page==='employees'?employees():S.page==='audits'?audits():S.page==='ranks'?ranksPage():S.page==='setup'?setup():dashboard()}
function table(rows,heads,fn){if(!rows.length)return '<div class="empty-state">Nothing to show.</div>';return `<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(fn).join('')}</tbody></table></div>`}
function dashboard(){let openT=visibleTasks().filter(t=>t.status!=='Completed').length, openK=visibleTickets().filter(t=>!['Resolved','Closed'].includes(t.status)).length, openC=visibleCases().filter(c=>!['Closed','Actioned'].includes(c.status)).length;return `<div class="grid four"><div class="stat-card"><p>Employees</p><strong>${S.employees.length}</strong></div><div class="stat-card"><p>Open Tasks</p><strong>${openT}</strong></div><div class="stat-card"><p>Open Tickets</p><strong>${openK}</strong></div><div class="stat-card"><p>IA Cases</p><strong>${openC}</strong></div></div><div class="grid two" style="margin-top:1rem"><section class="card"><h3>Your Profile</h3>${profile(S.emp)}</section><section class="card"><h3>Quick Actions</h3><div class="action-row"><button class="secondary-btn" data-jump="tasks">Tasks</button><button class="secondary-btn" data-jump="tickets">Tickets</button>${can(4)?'<button class="secondary-btn" data-jump="ia">IA Cases</button>':''}${can(6)?'<button class="secondary-btn" data-jump="employees">Add Employee</button>':''}</div><hr><p class="muted">Custom roles, supervisor assignments, multi-device login, and Internal Affairs are active.</p></section></div>`}
function profile(e){return table([e],['Employee ID','Discord','Supervisor','Department','Role','Status','Sessions'],x=>`<tr><td>${esc(x.employeeId)}</td><td>${esc(x.discordUsername)}</td><td>${esc(empName(x.supervisorId))}</td><td>${esc(x.department)}</td><td>${esc(x.rank)} ${badge('Level '+x.accessLevel)}</td><td>${badge(x.status)}</td><td>${badge(sessions(x).size+' linked')}</td></tr>`)}
function directory(){return `<div class="card"><div class="toolbar"><input id="search" placeholder="Search employees..."><button class="secondary-btn" data-refresh>Refresh</button></div><h3>Employees</h3><div id="empTable">${empRows(S.employees,false)}</div></div>`}
function empRows(rows,manage){return table(rows,['ID','Discord','Supervisor','Department','Role','Access','Status','Sessions',manage?'Actions':''],e=>`<tr><td>${esc(e.employeeId)}</td><td>${esc(e.discordUsername)}</td><td>${esc(empName(e.supervisorId))}</td><td>${esc(e.department)}</td><td>${esc(e.rank)}</td><td>${badge('Level '+e.accessLevel)}</td><td>${badge(e.status)}</td><td>${badge(sessions(e).size+' linked')}</td><td>${manage?`<select data-status="${esc(e.employeeId)}">${statuses.map(s=>`<option ${e.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="small-btn" data-reset="${esc(e.employeeId)}">Reset Sessions</button>`:''}</td></tr>`)}
function tasks(){return `<div class="grid two"><section class="card"><h3>Create Task</h3>${can(4)?taskForm():'<p class="muted">Supervisors and above can create tasks.</p>'}</section><section class="card"><h3>Tasks</h3>${taskRows(visibleTasks())}</section></div>`}
function taskForm(){return `<form id="taskForm" class="form-grid"><label>Title<input id="taskTitle" required></label><label>Assign To<select id="taskTo">${S.employees.filter(e=>ACTIVE.includes(e.status)).map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)}</option>`).join('')}</select></label><label>Priority<select id="taskPriority">${['Low','Normal','High','Critical'].map(p=>`<option>${p}</option>`).join('')}</select></label><label>Description<textarea id="taskDesc"></textarea></label><button class="primary-btn">Create Task</button></form>`}
function taskRows(rows){return table(rows,['Task','Assigned','Priority','Status','Update'],t=>`<tr><td><strong>${esc(t.title)}</strong><br><span class="muted">${esc(t.description||'')}</span></td><td>${esc(empName(t.assignedToEmployeeId))}</td><td>${badge(t.priority||'Normal')}</td><td>${badge(t.status)}</td><td><select data-task="${t.id}">${taskStatuses.map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`)}
function tickets(){return `<div class="grid two"><section class="card"><h3>Open Ticket</h3><form id="ticketForm" class="form-grid"><label>Category<select id="ticketCat"><option>Human Resources</option><option>Technology</option><option>Operations</option><option>Management Review</option><option>Other</option></select></label><label>Subject<input id="ticketSubject" required></label><label>Details<textarea id="ticketDetails"></textarea></label><button class="primary-btn">Submit Ticket</button></form></section><section class="card"><h3>Tickets</h3>${ticketRows(visibleTickets())}</section></div>`}
function ticketRows(rows){return table(rows,['Ticket','Created By','Status','Update'],t=>`<tr><td><strong>${esc(t.subject)}</strong><br><span class="muted">${esc(t.category)} — ${esc(t.details||'')}</span></td><td>${esc(empName(t.createdByEmployeeId))}</td><td>${badge(t.status)}</td><td><select data-ticket="${t.id}">${ticketStatuses.map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`)}
function ia(){return `<div class="grid two"><section class="card"><h3>Create IA Case</h3><form id="caseForm" class="form-grid"><label>Subject Employee<select id="caseSubject">${S.employees.map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)} (${esc(e.employeeId)})</option>`).join('')}</select></label><label>Assigned Investigator<select id="caseAssigned"><option value="">Unassigned</option>${S.employees.filter(e=>e.accessLevel>=4).map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)}</option>`).join('')}</select></label><label>Category<select id="caseType">${caseTypes.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Severity<select id="caseSeverity"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label>Summary<input id="caseSummary" required></label><label>Details<textarea id="caseDetails"></textarea></label><button class="primary-btn">Create Case</button></form></section><section class="card"><h3>IA Case Queue</h3>${caseRows(visibleCases())}</section></div>`}
function caseRows(rows){return table(rows,['Case','Subject','Assigned','Severity','Status','Update'],c=>`<tr><td><strong>${esc(c.caseId||c.id)}</strong><br>${esc(c.summary||'')}<br><span class="muted">${esc(c.category||'Other')} — ${esc(c.details||'')}</span></td><td>${esc(empName(c.subjectEmployeeId))}</td><td>${esc(empName(c.assignedToEmployeeId))}</td><td>${badge(c.severity||'Low')}</td><td>${badge(c.status)}</td><td><select data-case="${c.id}">${caseStatuses.map(s=>`<option ${c.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`)}
function employees(){return `<div class="grid two"><section class="card"><h3>Create Employee</h3><form id="empForm" class="form-grid"><label>Employee ID<input id="newId" required></label><label>Discord Username<input id="newUser" required></label><label>Supervisor<select id="newSupervisor"><option value="">No Supervisor</option>${S.employees.map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)} (${esc(e.employeeId)})</option>`).join('')}</select></label><label>Department<select id="newDept">${departments.map(d=>`<option>${d}</option>`).join('')}</select></label><label>Custom Role Title<input id="newRole" placeholder="Example: IA Investigator" required></label><label>Access Level<select id="newAccess">${accessLevels.map(l=>`<option value="${l}">Level ${l}</option>`).join('')}</select></label><label>Status<select id="newStatus">${statuses.map(s=>`<option>${s}</option>`).join('')}</select></label><button class="primary-btn">Create Employee</button></form></section><section class="card"><h3>Employee Records</h3>${empRows(S.employees,true)}</section></div>`}
function audits(){return `<div class="card"><h3>Audit Logs</h3>${table(S.audits,['Action','Actor','Details'],a=>`<tr><td>${esc(a.action)}</td><td>${esc(a.actorDiscordUsername)}</td><td><code>${esc(JSON.stringify(a.details||{}))}</code></td></tr>`)}</div>`}
function ranksPage(){return `<div class="card"><h3>Suggested Rank Structure</h3>${table(ranks,['Suggested Rank','Default Group','Default Access'],r=>`<tr><td>${r[0]}</td><td>${r[2]}</td><td>${badge('Level '+r[1])}</td></tr>`)}</div>`}
function setup(){return `<div class="grid two"><section class="card"><h3>Production Checklist</h3><p>${badge('Firestore')} ${badge('Rules')} ${badge('Custom Roles')} ${badge('Supervisors')} ${badge('Internal Affairs')}</p><hr><p class="muted">Deploy rules and hosting after every change. If account creation fails, make sure your employee record is active, linked to your current session, and level 6 or higher.</p></section><section class="card"><h3>Access Levels</h3><p class="muted">Level 8 Owner, Level 7 Executive, Level 6 Department Leadership, Level 5 Manager, Level 4 Supervisor/Investigator, Level 3 Senior Staff, Level 2 Staff, Level 1 Trainee, Level 0 Restricted.</p></section></div>`}
function wire(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=async()=>{S.page=b.dataset.jump;await load();render()});document.querySelectorAll('[data-refresh]').forEach(b=>b.onclick=async()=>{await load();S.notice='Refreshed.';render()});document.querySelector('#search')?.addEventListener('input',e=>{let q=norm(e.target.value), rows=q?S.employees.filter(x=>norm(JSON.stringify(x)).includes(q)):S.employees;document.querySelector('#empTable').innerHTML=empRows(rows,false)});document.querySelector('#taskForm')?.addEventListener('submit',createTask);document.querySelector('#ticketForm')?.addEventListener('submit',createTicket);document.querySelector('#empForm')?.addEventListener('submit',createEmployee);document.querySelector('#caseForm')?.addEventListener('submit',createCase);document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>run(async()=>{await updateDoc(doc(db,'tasks',x.dataset.task),{status:x.value,updatedAt:serverTimestamp(),updatedByEmployeeId:S.emp.employeeId});await log('TASK_STATUS_UPDATED',{taskId:x.dataset.task,status:x.value})},'Task updated.'));document.querySelectorAll('[data-ticket]').forEach(x=>x.onchange=()=>run(async()=>{await updateDoc(doc(db,'tickets',x.dataset.ticket),{status:x.value,updatedAt:serverTimestamp(),updatedByEmployeeId:S.emp.employeeId});await log('TICKET_STATUS_UPDATED',{ticketId:x.dataset.ticket,status:x.value})},'Ticket updated.'));document.querySelectorAll('[data-case]').forEach(x=>x.onchange=()=>run(async()=>{await updateDoc(doc(db,'iaCases',x.dataset.case),{status:x.value,updatedAt:serverTimestamp(),updatedByEmployeeId:S.emp.employeeId});await log('IA_CASE_STATUS_UPDATED',{caseId:x.dataset.case,status:x.value})},'IA case updated.'));document.querySelectorAll('[data-status]').forEach(x=>x.onchange=()=>run(async()=>{await updateDoc(doc(db,'employees',x.dataset.status),{status:x.value,updatedAt:serverTimestamp(),updatedByEmployeeId:S.emp.employeeId});await log('EMPLOYEE_STATUS_UPDATED',{employeeId:x.dataset.status,status:x.value})},'Employee updated.'));document.querySelectorAll('[data-reset]').forEach(x=>x.onclick=()=>run(async()=>{await updateDoc(doc(db,'employees',x.dataset.reset),{authUid:null,authUids:[],updatedAt:serverTimestamp(),updatedByEmployeeId:S.emp.employeeId});await log('EMPLOYEE_SESSIONS_RESET',{employeeId:x.dataset.reset})},'Sessions reset.'))}
async function createTask(e){e.preventDefault();await run(async()=>{await addDoc(collection(db,'tasks'),{title:val('#taskTitle'),assignedToEmployeeId:val('#taskTo'),priority:val('#taskPriority'),description:val('#taskDesc'),status:'Not Started',createdByEmployeeId:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await log('TASK_CREATED')},'Task created.')}
async function createTicket(e){e.preventDefault();await run(async()=>{await addDoc(collection(db,'tickets'),{category:val('#ticketCat'),subject:val('#ticketSubject'),details:val('#ticketDetails'),status:'Open',createdByEmployeeId:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await log('TICKET_CREATED')},'Ticket submitted.')}
async function createEmployee(e){e.preventDefault();await run(async()=>{let id=val('#newId').trim(), user=val('#newUser').trim(), level=Number(val('#newAccess')), role=val('#newRole').trim();if((await getDoc(doc(db,'employees',id))).exists())throw new Error('That Employee ID already exists.');await setDoc(doc(db,'employees',id),{employeeId:id,discordUsername:user,discordUsernameLower:norm(user),authUid:null,authUids:[],displayName:user,rank:role,rankGroup:'Custom',department:val('#newDept'),accessLevel:level,status:val('#newStatus'),supervisorId:val('#newSupervisor')||null,hireDate:today(),createdBy:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await log('EMPLOYEE_CREATED',{employeeId:id,role,level})},'Employee created.')}
async function createCase(e){e.preventDefault();await run(async()=>{let caseId='IA-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+Math.floor(1000+Math.random()*9000);await addDoc(collection(db,'iaCases'),{caseId,subjectEmployeeId:val('#caseSubject'),assignedToEmployeeId:val('#caseAssigned')||null,category:val('#caseType'),severity:val('#caseSeverity'),summary:val('#caseSummary'),details:val('#caseDetails'),status:'Open',createdByEmployeeId:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await log('IA_CASE_CREATED',{caseId})},'IA case created.')}
init();
