import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, addDoc, updateDoc, query, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { firebaseSettings } from './firebase-settings.js';

const app = initializeApp(firebaseSettings);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');
const ACTIVE = ['Active', 'Training', 'On Leave'];
let S = { user:null, emp:null, employees:[], courses:[], assignments:null, notice:'', questionCount:4 };
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = v => String(v || '').trim().toLowerCase();
const val = id => document.querySelector(id)?.value || '';
const sessions = e => new Set([e?.authUid, ...(Array.isArray(e?.authUids) ? e.authUids : [])].filter(Boolean));
const hasSession = e => sessions(e).has(S.user?.uid);
const can = n => Number(S.emp?.accessLevel || 0) >= n;
const badge = v => `<span class="badge blue">${esc(v)}</span>`;
const empName = id => S.employees.find(e => e.employeeId === id)?.discordUsername || id || 'Unknown';
const courseTitle = id => S.courses.find(c => c.id === id)?.title || id || 'Unknown';
const visibleCourses = () => S.courses.filter(c => !c.isDeleted && c.status !== 'Deleted');
const activeCourses = () => visibleCourses().filter(c => c.status !== 'Inactive' && c.status !== 'Archived');
async function anon(){ if(auth.currentUser) return auth.currentUser; return (await signInAnonymously(auth)).user; }
async function loadCore(){
  const [empSnap, courseSnap] = await Promise.all([
    getDocs(query(collection(db,'employees'),limit(250))),
    getDocs(query(collection(db,'trainingCourses'),limit(200)))
  ]);
  S.employees = empSnap.docs.map(d=>({id:d.id,...d.data()})).filter(e=>!e.isDeleted);
  S.courses = courseSnap.docs.map(d=>({id:d.id,...d.data()}));
}
async function loadAssignments(){ S.assignments = (await getDocs(query(collection(db,'trainingAssignments'),limit(300)))).docs.map(d=>({id:d.id,...d.data()})); }
async function loadResults(){ return (await getDocs(query(collection(db,'trainingResults'),limit(1000)))).docs.map(d=>({id:d.id,...d.data()})); }
async function log(action,details={}){ try{ await addDoc(collection(db,'auditLogs'),{action,details,actorUid:S.user?.uid||'system',actorEmployeeId:S.emp?.employeeId||'SYSTEM',actorDiscordUsername:S.emp?.discordUsername||'System',createdAt:serverTimestamp()}); }catch{} }
async function run(fn,msg){ try{ await fn(); S.notice=msg; await loadCore(); render(); }catch(e){ S.notice='Action failed: '+e.message; render(); } }
async function init(){ try{ S.user = await anon(); const saved = localStorage.getItem('cognitusEmployeeId'); if(saved){ const snap = await getDoc(doc(db,'employees',saved)); if(snap.exists() && hasSession(snap.data()) && ACTIVE.includes(snap.data().status)){ S.emp = snap.data(); await loadCore(); return render(); }} login(); }catch(e){ root.innerHTML = `<section class="login-page"><div class="login-card"><h1>Setup issue</h1><div class="notice error">${esc(e.message)}</div></div></section>`; } }
function login(msg=''){ root.innerHTML = `<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Training Admin</h1><p>Creation and assignments</p></div></div>${msg?`<div class="notice">${esc(msg)}</div>`:''}<form id="loginForm" class="form-grid"><label>Discord Username<input id="u" required></label><label>Employee ID<input id="id" required></label><button class="primary-btn">Enter Training Admin</button></form><hr><a class="secondary-btn" href="index.html" style="display:inline-block;text-decoration:none">Back to Staff Portal</a></div></section>`; document.querySelector('#loginForm').onsubmit = doLogin; }
async function doLogin(e){ e.preventDefault(); try{ S.user = await anon(); const employeeId = val('#id').trim(); const username = norm(val('#u')); const ref = doc(db,'employees',employeeId); const snap = await getDoc(ref); if(!snap.exists()) return login('No employee record was found.'); const emp = snap.data(); if(norm(emp.discordUsername)!==username) return login('The Discord Username does not match that Employee ID.'); if(!ACTIVE.includes(emp.status)) return login('This employee account is not active.'); const ids = [...sessions(emp),S.user.uid]; const updates = {authUids:[...new Set(ids)],lastLoginAt:serverTimestamp(),updatedAt:serverTimestamp()}; if(!emp.authUid) updates.authUid = S.user.uid; await updateDoc(ref,updates); S.emp = (await getDoc(ref)).data(); localStorage.setItem('cognitusEmployeeId',employeeId); await loadCore(); render(); }catch(e){ login('Login failed: '+e.message); } }
function render(){ if(!can(6)){ root.innerHTML = `<section class="login-page"><div class="login-card"><h1>Access Denied</h1><div class="notice error">Training Admin requires Level 6 or higher.</div><a class="secondary-btn" href="index.html">Back to Staff Portal</a></div></section>`; return; } const note = S.notice; S.notice=''; root.innerHTML = `<div class="portal-layout"><aside class="sidebar"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Training</h1><p>Admin</p></div></div><nav class="nav-list"><a class="nav-btn active" href="assignments.html">Training Admin</a><a class="nav-btn" href="learning.html">Quiz Portal</a><a class="nav-btn" href="index.html">Staff Portal</a></nav></aside><main class="main"><div class="portal-topbar"><div><h2>Training Admin</h2><p class="muted">This page now loads modules and employees first. Load assignments only when needed.</p></div><div class="topbar-actions">${badge(visibleCourses().length+' modules')}${badge((S.assignments?S.assignments.length:'not loaded')+' assignments')}</div></div>${note?`<div class="notice ${note.startsWith('Action failed')?'error':'success'}">${esc(note)}</div>`:''}<div class="grid two spacious"><section class="card"><h3>Create Training Module</h3>${moduleForm()}</section><section class="card"><h3>Assign Module</h3>${assignForm()}</section></div><div class="grid two spacious" style="margin-top:1.5rem"><section class="card"><h3>Modules</h3>${modulesTable()}</section><section class="card"><h3>Assignments</h3>${assignmentsTable()}</section></div></main></div>`; wire(); }
function moduleForm(){ return `<form id="moduleForm" class="form-grid"><label>Module Title<input id="moduleTitle" required></label><label>Lesson / Policy Content<textarea id="moduleContent" required></textarea></label><label>Module Type<select id="moduleType"><option>Staff Training</option><option>Competency Quiz</option><option>Policy Check</option><option>Onboarding</option></select></label><div id="questionsBox">${questionInputs()}</div><div class="action-row"><button type="button" class="secondary-btn" id="addQuestion">Add Question</button><button type="button" class="secondary-btn" id="removeQuestion">Remove Question</button></div><button class="primary-btn">Save Module</button></form>`; }
function questionInputs(){ return Array.from({length:S.questionCount},(_,i)=>`<div class="course-box"><strong>Question ${i+1}</strong><div class="form-split"><label>Question<input id="q${i}" ${i===0?'required':''}></label><label>Expected Answer<input id="a${i}" ${i===0?'required':''}></label></div></div>`).join(''); }
function assignForm(){ if(!activeCourses().length) return '<div class="empty-state">Create an active module first.</div>'; return `<form id="assignForm" class="form-grid"><label>Module<select id="courseId">${activeCourses().map(c=>`<option value="${esc(c.id)}">${esc(c.title)} (${esc(c.moduleType||'Training'})</option>`).join('')}</select></label><label>Assign To<select id="employeeId">${S.employees.filter(e=>ACTIVE.includes(e.status)).map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)} (${esc(e.employeeId)})</option>`).join('')}</select></label><label>Due Date<input id="dueDate" type="date"></label><button class="primary-btn">Assign Module</button></form>`; }
function modulesTable(){ if(!visibleCourses().length) return '<div class="empty-state">No modules created yet.</div>'; return `<div class="table-wrap"><table><thead><tr><th>Module</th><th>Type</th><th>Status</th><th>Questions</th><th>Actions</th></tr></thead><tbody>${visibleCourses().map(c=>`<tr><td><strong>${esc(c.title)}</strong><br><span class="muted">${esc((c.content||'').slice(0,120))}</span></td><td>${esc(c.moduleType||'Training')}</td><td>${badge(c.status||'Active')}</td><td>${Array.isArray(c.questions)?c.questions.length:0}</td><td><div class="action-stack"><button class="small-btn" data-toggle-course="${c.id}">${c.status==='Inactive'?'Reactivate':'Deactivate'}</button><button class="small-btn" data-archive-course="${c.id}">Delete Module</button></div></td></tr>`).join('')}</tbody></table></div>`; }
function assignmentsTable(){ if(!S.assignments) return '<div class="empty-state"><button class="primary-btn" id="loadAssignments">Load Assignments</button><p class="muted">Assignments are loaded on demand so this page opens faster.</p></div>'; if(!S.assignments.length) return '<div class="empty-state">No assignments created yet.</div>'; return `<div class="table-wrap"><table><thead><tr><th>Module</th><th>Employee</th><th>Due</th><th>Status</th><th>Actions</th></tr></thead><tbody>${S.assignments.map(a=>`<tr><td>${esc(courseTitle(a.courseId))}</td><td>${esc(empName(a.employeeId))}</td><td>${esc(a.dueDate || 'No due date')}</td><td>${badge(a.status || 'Assigned')}</td><td><div class="action-stack"><button class="small-btn" data-toggle-assignment="${a.id}">${a.status==='Inactive'?'Reactivate':'Deactivate'}</button><button class="small-btn" data-restart="${a.id}">Restart Person</button><button class="small-btn" data-clear="${a.id}">Delete Responses</button></div></td></tr>`).join('')}</tbody></table></div>`; }
function wire(){ document.querySelector('#moduleForm')?.addEventListener('submit',createModule); document.querySelector('#assignForm')?.addEventListener('submit',assign); document.querySelector('#loadAssignments')?.addEventListener('click',async()=>{S.notice='Loading assignments...';render();await loadAssignments();S.notice='Assignments loaded.';render();}); document.querySelector('#addQuestion')?.addEventListener('click',()=>{S.questionCount++;render();}); document.querySelector('#removeQuestion')?.addEventListener('click',()=>{S.questionCount=Math.max(1,S.questionCount-1);render();}); document.querySelectorAll('[data-toggle-course]').forEach(b=>b.onclick=()=>toggleCourse(b.dataset.toggleCourse)); document.querySelectorAll('[data-archive-course]').forEach(b=>b.onclick=()=>archiveCourse(b.dataset.archiveCourse)); document.querySelectorAll('[data-toggle-assignment]').forEach(b=>b.onclick=()=>toggleAssignment(b.dataset.toggleAssignment)); document.querySelectorAll('[data-restart]').forEach(b=>b.onclick=()=>restartAssignment(b.dataset.restart)); document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>clearResponses(b.dataset.clear)); }
async function createModule(e){ e.preventDefault(); await run(async()=>{ const questions=Array.from({length:S.questionCount},(_,i)=>({question:val('#q'+i),answer:norm(val('#a'+i))})).filter(q=>q.question&&q.answer); if(!questions.length) throw new Error('Add at least one question.'); await addDoc(collection(db,'trainingCourses'),{title:val('#moduleTitle'),content:val('#moduleContent'),moduleType:val('#moduleType'),questions,status:'Active',isDeleted:false,createdByEmployeeId:S.emp.employeeId,createdBy:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); await log('TRAINING_MODULE_CREATED',{title:val('#moduleTitle')}); }, 'Training module created.'); }
async function assign(e){ e.preventDefault(); await run(async()=>{ await addDoc(collection(db,'trainingAssignments'),{courseId:val('#courseId'),employeeId:val('#employeeId'),dueDate:val('#dueDate')||null,status:'Assigned',assignedByEmployeeId:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); S.assignments=null; await log('TRAINING_MODULE_ASSIGNED',{courseId:val('#courseId'),employeeId:val('#employeeId')}); }, 'Training module assigned. Click Load Assignments to refresh the assignment list.'); }
async function toggleCourse(id){ const c=S.courses.find(x=>x.id===id); await run(async()=>{ await updateDoc(doc(db,'trainingCourses',id),{status:c.status==='Inactive'?'Active':'Inactive',updatedByEmployeeId:S.emp.employeeId,updatedAt:serverTimestamp()}); await log('TRAINING_MODULE_TOGGLED',{courseId:id}); }, 'Module status changed.'); }
async function archiveCourse(id){ await run(async()=>{ await updateDoc(doc(db,'trainingCourses',id),{status:'Deleted',isDeleted:true,updatedByEmployeeId:S.emp.employeeId,updatedAt:serverTimestamp()}); await log('TRAINING_MODULE_DELETED',{courseId:id}); }, 'Module deleted from active use.'); }
async function toggleAssignment(id){ const a=S.assignments.find(x=>x.id===id); await run(async()=>{ await updateDoc(doc(db,'trainingAssignments',id),{status:a.status==='Inactive'?'Assigned':'Inactive',updatedByEmployeeId:S.emp.employeeId,updatedAt:serverTimestamp()}); await loadAssignments(); await log('TRAINING_ASSIGNMENT_TOGGLED',{assignmentId:id}); }, 'Assignment status changed.'); }
async function restartAssignment(id){ const a=S.assignments.find(x=>x.id===id); await run(async()=>{ await updateDoc(doc(db,'trainingAssignments',id),{status:'Assigned',restartAt:serverTimestamp(),updatedByEmployeeId:S.emp.employeeId,updatedAt:serverTimestamp()}); const results=await loadResults(); for(const r of results.filter(r=>r.employeeId===a.employeeId&&r.courseId===a.courseId&&!r.isDeleted)){ await updateDoc(doc(db,'trainingResults',r.id),{isDeleted:true,status:'Deleted',updatedByEmployeeId:S.emp.employeeId,updatedAt:serverTimestamp()}); } await loadAssignments(); await log('TRAINING_ATTEMPT_RESTARTED',{assignmentId:id}); }, 'Person restarted. Previous responses deleted.'); }
async function clearResponses(id){ const a=S.assignments.find(x=>x.id===id); await run(async()=>{ const results=await loadResults(); for(const r of results.filter(r=>r.employeeId===a.employeeId&&r.courseId===a.courseId&&!r.isDeleted)){ await updateDoc(doc(db,'trainingResults',r.id),{isDeleted:true,status:'Deleted',updatedByEmployeeId:S.emp.employeeId,updatedAt:serverTimestamp()}); } await loadAssignments(); await log('TRAINING_RESPONSES_DELETED',{assignmentId:id}); }, 'Responses deleted.'); }
init();
