import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, addDoc, updateDoc, query, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { firebaseSettings } from './firebase-settings.js';

const app = initializeApp(firebaseSettings);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');
const ACTIVE = ['Active', 'Training', 'On Leave'];
let S = { user:null, emp:null, employees:[], courses:[], assignments:[], notice:'' };
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = v => String(v || '').trim().toLowerCase();
const val = id => document.querySelector(id)?.value || '';
const sessions = e => new Set([e?.authUid, ...(Array.isArray(e?.authUids) ? e.authUids : [])].filter(Boolean));
const hasSession = e => sessions(e).has(S.user?.uid);
const can = n => Number(S.emp?.accessLevel || 0) >= n;
const badge = v => `<span class="badge blue">${esc(v)}</span>`;
const empName = id => S.employees.find(e => e.employeeId === id)?.discordUsername || id || 'Unknown';
const courseTitle = id => S.courses.find(c => c.id === id)?.title || id || 'Unknown';
async function anon(){ if(auth.currentUser) return auth.currentUser; return (await signInAnonymously(auth)).user; }
async function load(){ S.employees = (await getDocs(query(collection(db,'employees'),orderBy('employeeId'),limit(500)))).docs.map(d=>({id:d.id,...d.data()})); S.courses = (await getDocs(query(collection(db,'trainingCourses'),orderBy('createdAt','desc'),limit(300)))).docs.map(d=>({id:d.id,...d.data()})); S.assignments = (await getDocs(query(collection(db,'trainingAssignments'),orderBy('createdAt','desc'),limit(500)))).docs.map(d=>({id:d.id,...d.data()})); }
async function log(action,details={}){ try{ await addDoc(collection(db,'auditLogs'),{action,details,actorUid:S.user?.uid||'system',actorEmployeeId:S.emp?.employeeId||'SYSTEM',actorDiscordUsername:S.emp?.discordUsername||'System',createdAt:serverTimestamp()}); }catch{} }
async function run(fn,msg){ try{ await fn(); S.notice=msg; await load(); render(); }catch(e){ S.notice='Action failed: '+e.message; render(); } }
async function init(){ try{ S.user = await anon(); const saved = localStorage.getItem('cognitusEmployeeId'); if(saved){ const snap = await getDoc(doc(db,'employees',saved)); if(snap.exists() && hasSession(snap.data()) && ACTIVE.includes(snap.data().status)){ S.emp = snap.data(); await load(); return render(); }} login(); }catch(e){ root.innerHTML = `<section class="login-page"><div class="login-card"><h1>Setup issue</h1><div class="notice error">${esc(e.message)}</div></div></section>`; } }
function login(msg=''){ root.innerHTML = `<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Training Assignments</h1><p>Leadership tools</p></div></div>${msg?`<div class="notice">${esc(msg)}</div>`:''}<form id="loginForm" class="form-grid"><label>Discord Username<input id="u" required></label><label>Employee ID<input id="id" required></label><button class="primary-btn">Enter Assignments</button></form><hr><a class="secondary-btn" href="index.html" style="display:inline-block;text-decoration:none">Back to Staff Portal</a></div></section>`; document.querySelector('#loginForm').onsubmit = doLogin; }
async function doLogin(e){ e.preventDefault(); try{ S.user = await anon(); const employeeId = val('#id').trim(); const username = norm(val('#u')); const ref = doc(db,'employees',employeeId); const snap = await getDoc(ref); if(!snap.exists()) return login('No employee record was found.'); const emp = snap.data(); if(norm(emp.discordUsername)!==username) return login('The Discord Username does not match that Employee ID.'); if(!ACTIVE.includes(emp.status)) return login('This employee account is not active.'); const ids = [...sessions(emp),S.user.uid]; const updates = {authUids:[...new Set(ids)],lastLoginAt:serverTimestamp(),updatedAt:serverTimestamp()}; if(!emp.authUid) updates.authUid = S.user.uid; await updateDoc(ref,updates); S.emp = (await getDoc(ref)).data(); localStorage.setItem('cognitusEmployeeId',employeeId); await load(); render(); }catch(e){ login('Login failed: '+e.message); } }
function render(){ if(!can(6)){ root.innerHTML = `<section class="login-page"><div class="login-card"><h1>Access Denied</h1><div class="notice error">Training assignments require Level 6 or higher.</div><a class="secondary-btn" href="index.html">Back to Staff Portal</a></div></section>`; return; } const note = S.notice; S.notice=''; root.innerHTML = `<div class="portal-layout"><aside class="sidebar"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Assignments</h1><p>Learning</p></div></div><nav class="nav-list"><a class="nav-btn active" href="assignments.html">Training Assignments</a><a class="nav-btn" href="learning.html">Learning Portal</a><a class="nav-btn" href="index.html">Staff Portal</a></nav></aside><main class="main"><div class="portal-topbar"><div><h2>Training Assignments</h2><p class="muted">${esc(S.emp.discordUsername)} • Level ${esc(S.emp.accessLevel)}</p></div><div class="topbar-actions">${badge(S.courses.length+' modules')}${badge(S.assignments.length+' assignments')}</div></div>${note?`<div class="notice ${note.startsWith('Action failed')?'error':'success'}">${esc(note)}</div>`:''}<div class="grid two spacious"><section class="card"><h3>Assign Module</h3>${form()}</section><section class="card"><h3>Assignment List</h3>${table()}</section></div></main></div>`; document.querySelector('#assignForm').onsubmit = assign; }
function form(){ if(!S.courses.length) return '<div class="empty-state">Create a learning module first in the Learning Portal.</div>'; return `<form id="assignForm" class="form-grid"><label>Learning Module<select id="courseId">${S.courses.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')}</select></label><label>Assign To<select id="employeeId">${S.employees.filter(e=>ACTIVE.includes(e.status)).map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)} (${esc(e.employeeId)})</option>`).join('')}</select></label><label>Due Date<input id="dueDate" type="date"></label><button class="primary-btn">Assign Module</button></form>`; }
function table(){ if(!S.assignments.length) return '<div class="empty-state">No assignments created yet.</div>'; return `<div class="table-wrap"><table><thead><tr><th>Module</th><th>Employee</th><th>Due</th><th>Status</th><th>Assigned By</th></tr></thead><tbody>${S.assignments.map(a=>`<tr><td>${esc(courseTitle(a.courseId))}</td><td>${esc(empName(a.employeeId))}</td><td>${esc(a.dueDate || 'No due date')}</td><td>${badge(a.status || 'Assigned')}</td><td>${esc(empName(a.assignedByEmployeeId))}</td></tr>`).join('')}</tbody></table></div>`; }
async function assign(e){ e.preventDefault(); await run(async()=>{ await addDoc(collection(db,'trainingAssignments'),{courseId:val('#courseId'),employeeId:val('#employeeId'),dueDate:val('#dueDate')||null,status:'Assigned',assignedByEmployeeId:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); await log('TRAINING_MODULE_ASSIGNED',{courseId:val('#courseId'),employeeId:val('#employeeId')}); }, 'Training module assigned.'); }
init();
