import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, updateDoc, addDoc, query, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { firebaseSettings } from './firebase-settings.js';

const app = initializeApp(firebaseSettings);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');
const activeStatuses = ['Active', 'Training', 'On Leave'];
const statuses = ['Active', 'Training', 'On Leave', 'Suspended', 'Resigned', 'Terminated', 'Archived'];
const departments = ['Executive Office','Human Resources','Accreditation Services','Records & Intelligence','Investigations','Operations','Technology','Public Relations','Internal Affairs'];
const levels = [0,1,2,3,4,5,6,7,8];
let currentUser = null, currentEmployee = null, employees = [], notice = '';
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = v => String(v || '').trim().toLowerCase();
const val = id => document.querySelector(id)?.value || '';
const sessions = e => new Set([e?.authUid, ...(Array.isArray(e?.authUids) ? e.authUids : [])].filter(Boolean));
const hasSession = e => sessions(e).has(currentUser?.uid);
const badge = v => `<span class="badge blue">${esc(v)}</span>`;
async function anon(){ if(auth.currentUser) return auth.currentUser; return (await signInAnonymously(auth)).user; }
async function load(){ employees = (await getDocs(query(collection(db,'employees'),orderBy('employeeId'),limit(500)))).docs.map(d => ({id:d.id,...d.data()})).filter(e=>!e.isDeleted); }
async function log(action, details={}){ try{ await addDoc(collection(db,'auditLogs'),{action,details,actorUid:currentUser?.uid||'system',actorEmployeeId:currentEmployee?.employeeId||'SYSTEM',actorDiscordUsername:currentEmployee?.discordUsername||'System',createdAt:serverTimestamp()}); }catch{} }
async function init(){ try{ currentUser = await anon(); const saved = localStorage.getItem('cognitusEmployeeId'); if(saved){ const snap = await getDoc(doc(db,'employees',saved)); if(snap.exists() && hasSession(snap.data()) && activeStatuses.includes(snap.data().status)){ currentEmployee = snap.data(); await load(); return render(); }} renderLogin(); }catch(e){ root.innerHTML = `<section class="login-page"><div class="login-card"><h1>Setup issue</h1><div class="notice error">${esc(e.message)}</div></div></section>`; }}
function renderLogin(msg=''){ root.innerHTML = `<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Employee Editor</h1><p>Leadership tools</p></div></div>${msg?`<div class="notice">${esc(msg)}</div>`:''}<form id="loginForm" class="form-grid"><label>Discord Username<input id="u" required></label><label>Employee ID<input id="id" required></label><button class="primary-btn">Enter Editor</button></form><hr><a class="secondary-btn" href="index.html" style="display:inline-block;text-decoration:none">Back to Staff Portal</a></div></section>`; document.querySelector('#loginForm').onsubmit = login; }
async function login(e){ e.preventDefault(); try{ currentUser = await anon(); const employeeId = val('#id').trim(); const username = norm(val('#u')); const ref = doc(db,'employees',employeeId); const snap = await getDoc(ref); if(!snap.exists()) return renderLogin('No employee record was found.'); const emp = snap.data(); if(norm(emp.discordUsername)!==username) return renderLogin('The Discord Username does not match that Employee ID.'); if(!activeStatuses.includes(emp.status)) return renderLogin('This employee account is not active.'); const ids = [...sessions(emp), currentUser.uid]; const updates = {authUids:[...new Set(ids)], lastLoginAt:serverTimestamp(), updatedAt:serverTimestamp()}; if(!emp.authUid) updates.authUid = currentUser.uid; await updateDoc(ref, updates); currentEmployee = (await getDoc(ref)).data(); localStorage.setItem('cognitusEmployeeId',employeeId); await load(); render(); }catch(e){ renderLogin('Login failed: '+e.message); }}
function render(){ if(Number(currentEmployee.accessLevel||0)<6){ root.innerHTML = `<section class="login-page"><div class="login-card"><h1>Access Denied</h1><div class="notice error">Employee editing requires Level 6 or higher.</div><a class="secondary-btn" href="index.html">Back to Staff Portal</a></div></section>`; return; } root.innerHTML = `<div class="portal-layout"><aside class="sidebar"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Editor</h1><p>Employees</p></div></div><nav class="nav-list"><a class="nav-btn active" href="employee-edit.html">Edit Employees</a><a class="nav-btn" href="assignments.html">Training Admin</a><a class="nav-btn" href="index.html">Staff Portal</a></nav></aside><main class="main"><div class="portal-topbar"><div><h2>Edit Employees</h2><p class="muted">${esc(currentEmployee.discordUsername)} • Level ${esc(currentEmployee.accessLevel)}</p></div><div class="topbar-actions">${badge(employees.length+' employees')}</div></div>${notice?`<div class="notice ${notice.startsWith('Action failed')?'error':'success'}">${esc(notice)}</div>`:''}<div class="grid two spacious"><section class="card"><h3>Edit Employee Record</h3>${form()}</section><section class="card"><h3>Employee Directory</h3>${table()}</section></div></main></div>`; wire(); }
function employeeOptions(selected=''){ return `<option value="">No Supervisor</option>${employees.map(e=>`<option value="${esc(e.employeeId)}" ${e.employeeId===selected?'selected':''}>${esc(e.discordUsername)} (${esc(e.employeeId)})</option>`).join('')}`; }
function form(){ return `<form id="editForm" class="form-grid"><label>Select Employee<select id="editId"><option value="">Choose an employee...</option>${employees.map(e=>`<option value="${esc(e.employeeId)}">${esc(e.discordUsername)} (${esc(e.employeeId)})</option>`).join('')}</select></label><label>Employee ID / User ID<input id="editEmployeeId" required><span class="muted">For potential hires, use PH-CQ-## such as PH-CQ-01.</span></label><label>Discord Username<input id="editUser" required></label><label>Supervisor<select id="editSupervisor">${employeeOptions()}</select></label><label>Department<select id="editDept">${departments.map(d=>`<option>${esc(d)}</option>`).join('')}</select></label><label>Custom Role Title<input id="editRole" required></label><label>Access Level<select id="editAccess">${levels.map(l=>`<option value="${l}">Level ${l}</option>`).join('')}</select></label><label>Status<select id="editStatus">${statuses.map(s=>`<option>${esc(s)}</option>`).join('')}</select></label><div class="action-row"><button class="primary-btn">Save Changes</button><button type="button" class="danger-btn" id="deleteEmployee">Delete Employee</button></div></form>`; }
function table(){ if(!employees.length) return '<div class="empty-state">No employees found.</div>'; return `<div class="table-wrap"><table><thead><tr><th>ID</th><th>Discord</th><th>Supervisor</th><th>Department</th><th>Role</th><th>Access</th><th>Status</th><th>Action</th></tr></thead><tbody>${employees.map(e=>`<tr><td>${esc(e.employeeId)}</td><td>${esc(e.discordUsername)}</td><td>${esc(employees.find(x=>x.employeeId===e.supervisorId)?.discordUsername||'None')}</td><td>${esc(e.department)}</td><td>${esc(e.rank)}</td><td>${badge('Level '+e.accessLevel)}</td><td>${badge(e.status)}</td><td><button class="small-btn" data-pick="${esc(e.employeeId)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`; }
function fill(id){ const e = employees.find(x=>x.employeeId===id); if(!e) return; document.querySelector('#editId').value=e.employeeId; document.querySelector('#editEmployeeId').value=e.employeeId||''; document.querySelector('#editUser').value=e.discordUsername||''; document.querySelector('#editSupervisor').value=e.supervisorId||''; document.querySelector('#editDept').value=e.department||departments[0]; document.querySelector('#editRole').value=e.rank||''; document.querySelector('#editAccess').value=String(e.accessLevel??0); document.querySelector('#editStatus').value=e.status||'Active'; }
function wire(){ document.querySelector('#editId').onchange = e => fill(e.target.value); document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{ fill(b.dataset.pick); document.querySelector('#editForm').scrollIntoView({behavior:'smooth',block:'start'}); }); document.querySelector('#editForm').onsubmit = save; document.querySelector('#deleteEmployee').onclick = deleteEmployee; }
async function save(e){ e.preventDefault(); try{ const oldId = val('#editId').trim(); const newId = val('#editEmployeeId').trim(); if(!oldId) throw new Error('Choose an employee first.'); if(!newId) throw new Error('Employee ID cannot be blank.'); const existing = employees.find(x=>x.employeeId===oldId); if(!existing) throw new Error('Original employee record was not found.'); const username = val('#editUser').trim(); const data = {...existing, employeeId:newId, discordUsername:username, discordUsernameLower:norm(username), displayName:username, supervisorId:val('#editSupervisor')||null, department:val('#editDept'), rank:val('#editRole').trim(), rankGroup:'Custom', accessLevel:Number(val('#editAccess')), status:val('#editStatus'), isDeleted:false, updatedByEmployeeId:currentEmployee.employeeId, updatedAt:serverTimestamp()}; if(newId !== oldId){ if((await getDoc(doc(db,'employees',newId))).exists()) throw new Error('That new Employee ID already exists.'); await setDoc(doc(db,'employees',newId),data); await updateDoc(doc(db,'employees',oldId),{status:'Archived',isDeleted:true,replacedByEmployeeId:newId,updatedByEmployeeId:currentEmployee.employeeId,updatedAt:serverTimestamp()}); await log('EMPLOYEE_ID_CHANGED',{oldId,newId}); if(localStorage.getItem('cognitusEmployeeId')===oldId) localStorage.setItem('cognitusEmployeeId',newId); } else { await updateDoc(doc(db,'employees',oldId),data); await log('EMPLOYEE_EDITED',{employeeId:oldId}); } notice='Employee record saved.'; await load(); render(); }catch(e){ notice='Action failed: '+e.message; render(); }}
async function deleteEmployee(){ try{ const id = val('#editId').trim(); if(!id) throw new Error('Choose an employee first.'); if(id===currentEmployee.employeeId) throw new Error('You cannot delete your own logged-in record.'); await updateDoc(doc(db,'employees',id),{status:'Archived',isDeleted:true,authUid:null,authUids:[],updatedByEmployeeId:currentEmployee.employeeId,updatedAt:serverTimestamp()}); await log('EMPLOYEE_DELETED',{employeeId:id}); notice='Employee deleted from active use.'; await load(); render(); }catch(e){ notice='Action failed: '+e.message; render(); }}
init();
