import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, addDoc, updateDoc, query, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { firebaseSettings } from './firebase-settings.js';

const app = initializeApp(firebaseSettings);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');
const ACTIVE = ['Active', 'Training', 'On Leave'];
let S = { user:null, emp:null, employees:[], courses:[], assignments:[], results:[], notice:'' };
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = v => String(v || '').trim().toLowerCase();
const val = id => document.querySelector(id)?.value || '';
const sessions = e => new Set([e?.authUid, ...(Array.isArray(e?.authUids) ? e.authUids : [])].filter(Boolean));
const hasSession = e => sessions(e).has(S.user?.uid);
const badge = v => `<span class="badge blue">${esc(v)}</span>`;
const isPH = () => /^PH-CQ-\d+$/i.test(S.emp?.employeeId || '');
async function anon(){ if(auth.currentUser) return auth.currentUser; return (await signInAnonymously(auth)).user; }
async function load(){ S.employees=(await getDocs(query(collection(db,'employees'),orderBy('employeeId'),limit(500)))).docs.map(d=>({id:d.id,...d.data()})); S.courses=(await getDocs(query(collection(db,'trainingCourses'),orderBy('createdAt','desc'),limit(300)))).docs.map(d=>({id:d.id,...d.data()})); S.assignments=(await getDocs(query(collection(db,'trainingAssignments'),orderBy('createdAt','desc'),limit(500)))).docs.map(d=>({id:d.id,...d.data()})); S.results=(await getDocs(query(collection(db,'trainingResults'),orderBy('createdAt','desc'),limit(500)))).docs.map(d=>({id:d.id,...d.data()})); }
async function log(action,details={}){ try{ await addDoc(collection(db,'auditLogs'),{action,details,actorUid:S.user?.uid||'system',actorEmployeeId:S.emp?.employeeId||'SYSTEM',actorDiscordUsername:S.emp?.discordUsername||'System',createdAt:serverTimestamp()}); }catch{} }
async function run(fn,msg){ try{ await fn(); S.notice=msg; await load(); render(); }catch(e){ S.notice='Action failed: '+e.message; render(); } }
async function init(){ try{ S.user=await anon(); const saved=localStorage.getItem('cognitusEmployeeId'); if(saved){ const snap=await getDoc(doc(db,'employees',saved)); if(snap.exists()&&hasSession(snap.data())&&ACTIVE.includes(snap.data().status)){ S.emp=snap.data(); await load(); return render(); }} login(); }catch(e){ root.innerHTML=`<section class="login-page"><div class="login-card"><h1>Setup issue</h1><div class="notice error">${esc(e.message)}</div></div></section>`; } }
function login(msg=''){ root.innerHTML=`<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>${msg&&msg.includes('PH')?'Competency Quiz':'Quiz Portal'}</h1><p>Assigned modules only</p></div></div>${msg?`<div class="notice">${esc(msg)}</div>`:''}<form id="loginForm" class="form-grid"><label>Discord Username<input id="u" required></label><label>Employee ID<input id="id" required placeholder="Staff ID or PH-CQ-##"></label><button class="primary-btn">Enter Quiz Portal</button></form><hr><a class="secondary-btn" href="index.html" style="display:inline-block;text-decoration:none">Back to Staff Portal</a></div></section>`; document.querySelector('#loginForm').onsubmit=doLogin; }
async function doLogin(e){ e.preventDefault(); try{ S.user=await anon(); const employeeId=val('#id').trim(); const username=norm(val('#u')); const ref=doc(db,'employees',employeeId); const snap=await getDoc(ref); if(!snap.exists()) return login('No employee or potential-hire record was found.'); const emp=snap.data(); if(norm(emp.discordUsername)!==username) return login('The Discord Username does not match that ID.'); if(!ACTIVE.includes(emp.status)) return login('This record is not currently active.'); const ids=[...sessions(emp),S.user.uid]; const updates={authUids:[...new Set(ids)],lastLoginAt:serverTimestamp(),updatedAt:serverTimestamp()}; if(!emp.authUid) updates.authUid=S.user.uid; await updateDoc(ref,updates); S.emp=(await getDoc(ref)).data(); localStorage.setItem('cognitusEmployeeId',employeeId); await load(); render(); }catch(e){ login('Login failed: '+e.message); } }
function myResults(){ return S.results.filter(r=>!r.isDeleted&&r.employeeId===S.emp.employeeId); }
function activeAssignments(){ return S.assignments.filter(a=>a.employeeId===S.emp.employeeId&&a.status!=='Inactive'&&!a.isDeleted); }
function assignedCourses(){ const ids=new Set(activeAssignments().map(a=>a.courseId)); return S.courses.filter(c=>ids.has(c.id)&&!c.isDeleted&&c.status!=='Deleted'&&c.status!=='Inactive'&&c.status!=='Archived'); }
function render(){ const note=S.notice; S.notice=''; const courses=assignedCourses(); root.innerHTML=`<div class="portal-layout"><aside class="sidebar"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>${isPH()?'PH Quiz':'Quiz'}</h1><p>${isPH()?'Competency Check':'Learning Portal'}</p></div></div><nav class="nav-list"><a class="nav-btn active" href="learning.html">Quiz Portal</a>${isPH()?'':'<a class="nav-btn" href="index.html">Staff Portal</a><a class="nav-btn" href="assignments.html">Training Admin</a>'}</nav></aside><main class="main"><div class="portal-topbar"><div><h2>${isPH()?'Potential Hire Competency Quiz':'Assigned Quizzes'}</h2><p class="muted">${esc(S.emp.discordUsername)} • ${esc(S.emp.employeeId)}</p></div><div class="topbar-actions">${badge(courses.length+' assigned')}${badge(myResults().filter(r=>r.passed).length+' passed')}</div></div>${note?`<div class="notice ${note.startsWith('Action failed')?'error':'success'}">${esc(note)}</div>`:''}${courses.length?courses.map(courseBox).join(''):'<section class="card"><h3>No Assigned Quiz</h3><div class="empty-state">No active quiz/module is assigned to this account.</div></section>'}${resultsPanel()}</main></div>`; wire(); }
function courseBox(c){ const result=myResults().find(r=>r.courseId===c.id); const assignment=activeAssignments().find(a=>a.courseId===c.id); const qs=Array.isArray(c.questions)?c.questions:[]; return `<section class="card"><div class="course-head"><div><h3>${esc(c.title)}</h3><p class="muted">${assignment?.dueDate?'Due: '+esc(assignment.dueDate):'No due date'} ${isPH()?'• Competency Quiz':''}</p></div>${result?badge((result.passed?'Passed':'Needs Review')+' '+result.score+'%'):badge('Not Submitted')}</div><p>${esc(c.content||'')}</p><form class="quiz-form" data-course="${c.id}">${qs.map((q,i)=>`<label>${esc(q.question)}<input name="q${i}" placeholder="Your answer" required></label>`).join('')}<button class="primary-btn">Submit Quiz</button></form></section>`; }
function resultsPanel(){ const rows=myResults(); if(!rows.length) return ''; return `<section class="card"><h3>My Results</h3><div class="table-wrap"><table><thead><tr><th>Module</th><th>Score</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(S.courses.find(c=>c.id===r.courseId)?.title||r.courseId)}</td><td>${badge((r.score||0)+'%')}</td><td>${badge(r.passed?'Passed':'Needs Review')}</td></tr>`).join('')}</tbody></table></div></section>`; }
function wire(){ document.querySelectorAll('.quiz-form').forEach(f=>f.onsubmit=submitQuiz); }
async function submitQuiz(e){ e.preventDefault(); await run(async()=>{ const course=S.courses.find(c=>c.id===e.target.dataset.course); const qs=course.questions||[]; let correct=0; qs.forEach((q,i)=>{ if(norm(e.target.querySelector(`[name=q${i}]`)?.value)===norm(q.answer)) correct++; }); const score=qs.length?Math.round(correct/qs.length*100):100; const passed=score>=70; await addDoc(collection(db,'trainingResults'),{courseId:course.id,employeeId:S.emp.employeeId,score,passed,correct,total:qs.length,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); await log('QUIZ_SUBMITTED',{courseId:course.id,score,employeeId:S.emp.employeeId}); }, 'Quiz submitted.'); }
init();
