import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, addDoc, updateDoc, query, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { firebaseSettings } from './firebase-settings.js';

const app = initializeApp(firebaseSettings);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');
const ACTIVE = ['Active', 'Training', 'On Leave'];
let S = { user:null, emp:null, courses:[], results:[], notice:'' };
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = v => String(v || '').trim().toLowerCase();
const val = id => document.querySelector(id)?.value || '';
const can = n => Number(S.emp?.accessLevel || 0) >= n;
const sessions = e => new Set([e?.authUid, ...(Array.isArray(e?.authUids) ? e.authUids : [])].filter(Boolean));
const hasSession = e => sessions(e).has(S.user?.uid);
function badge(v){return `<span class="badge blue">${esc(v)}</span>`}
async function anon(){if(auth.currentUser)return auth.currentUser;return (await signInAnonymously(auth)).user}
async function log(action, details={}){try{await addDoc(collection(db,'auditLogs'),{action,details,actorUid:S.user?.uid||'system',actorEmployeeId:S.emp?.employeeId||'SYSTEM',actorDiscordUsername:S.emp?.discordUsername||'System',createdAt:serverTimestamp()})}catch{}}
async function run(fn,msg){try{await fn();S.notice=msg;await load();render()}catch(e){S.notice='Action failed: '+e.message;render()}}
async function load(){S.courses=(await getDocs(query(collection(db,'trainingCourses'),orderBy('createdAt','desc'),limit(200)))).docs.map(d=>({id:d.id,...d.data()}));S.results=(await getDocs(query(collection(db,'trainingResults'),orderBy('createdAt','desc'),limit(400)))).docs.map(d=>({id:d.id,...d.data()}))}
async function init(){try{S.user=await anon();let saved=localStorage.getItem('cognitusEmployeeId');if(saved){let snap=await getDoc(doc(db,'employees',saved));if(snap.exists()&&hasSession(snap.data())&&ACTIVE.includes(snap.data().status)){S.emp=snap.data();await load();return render()}}login()}catch(e){root.innerHTML=`<section class="login-page"><div class="login-card"><h1>Setup issue</h1><div class="notice error">${esc(e.message)}</div></div></section>`}}
function login(msg=''){root.innerHTML=`<section class="login-page"><div class="login-card"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Cognitus Learning</h1><p>Lessons and checks</p></div></div>${msg?`<div class="notice">${esc(msg)}</div>`:''}<form id="loginForm" class="form-grid"><label>Discord Username<input id="u" required></label><label>Employee ID<input id="id" required></label><button class="primary-btn">Enter Learning Portal</button></form><hr><a class="secondary-btn" href="index.html" style="display:inline-block;text-decoration:none">Back to Staff Portal</a></div></section>`;document.querySelector('#loginForm').onsubmit=doLogin}
async function doLogin(e){e.preventDefault();try{S.user=await anon();let employeeId=val('#id').trim(),username=norm(val('#u')),ref=doc(db,'employees',employeeId),snap=await getDoc(ref);if(!snap.exists())return login('No employee record was found.');let emp=snap.data();if(norm(emp.discordUsername)!==username)return login('The Discord Username does not match that Employee ID.');if(!ACTIVE.includes(emp.status))return login('This employee account is not active.');let ids=[...sessions(emp),S.user.uid],updates={authUids:[...new Set(ids)],lastLoginAt:serverTimestamp(),updatedAt:serverTimestamp()};if(!emp.authUid)updates.authUid=S.user.uid;await updateDoc(ref,updates);S.emp=(await getDoc(ref)).data();localStorage.setItem('cognitusEmployeeId',employeeId);await load();render()}catch(e){login('Login failed: '+e.message)}}
function myResults(){return S.results.filter(r=>r.employeeId===S.emp.employeeId)}
function render(){let notice=S.notice;S.notice='';root.innerHTML=`<div class="portal-layout"><aside class="sidebar"><div class="brand-row"><div class="brand-mark">CS</div><div><h1>Learning</h1><p>Staff Portal</p></div></div><nav class="nav-list"><a class="nav-btn active" href="learning.html">Learning</a><a class="nav-btn" href="index.html">Staff Portal</a></nav></aside><main class="main"><div class="portal-topbar"><div><h2>Learning Portal</h2><p class="muted">${esc(S.emp.discordUsername)} • ${esc(S.emp.employeeId)}</p></div><div class="topbar-actions">${badge('Courses '+S.courses.length)}${badge('Passed '+myResults().filter(r=>r.passed).length)}</div></div>${notice?`<div class="notice ${notice.startsWith('Action failed')?'error':'success'}">${esc(notice)}</div>`:''}<div class="grid two spacious">${can(6)?adminPanel():''}${coursePanel()}</div>${resultsPanel()}</main></div>`;wire()}
function panel(title,body){return `<section class="card"><h3>${title}</h3>${body}</section>`}
function adminPanel(){return panel('Create Learning Module',`<form id="courseForm" class="form-grid"><label>Title<input id="courseTitle" required></label><label>Lesson Content<textarea id="courseContent" required placeholder="Write the lesson or policy here."></textarea></label><div class="form-split"><label>Check Question 1<input id="q1" required></label><label>Expected Answer 1<input id="a1" required></label></div><div class="form-split"><label>Check Question 2<input id="q2"></label><label>Expected Answer 2<input id="a2"></label></div><div class="form-split"><label>Check Question 3<input id="q3"></label><label>Expected Answer 3<input id="a3"></label></div><button class="primary-btn">Create Module</button></form>`)}
function coursePanel(){if(!S.courses.length)return panel('Available Modules','<div class="empty-state">No modules have been created yet.</div>');let results=myResults();return panel('Available Modules',S.courses.map(c=>{let r=results.find(x=>x.courseId===c.id),qs=Array.isArray(c.questions)?c.questions:[];return `<div class="course-box"><div class="course-head"><strong>${esc(c.title)}</strong>${r?badge((r.passed?'Passed':'Needs Review')+' '+r.score+'%'):badge('Not Completed')}</div><p class="muted">${esc(c.content||'')}</p><form class="quiz-form" data-course="${c.id}">${qs.map((q,i)=>`<label>${esc(q.question)}<input name="q${i}" placeholder="Your answer"></label>`).join('')}<button class="secondary-btn">Submit Check</button></form></div>`}).join(''))}
function resultsPanel(){let rows=myResults();if(!rows.length)return panel('My Results','<div class="empty-state">No completed learning checks yet.</div>');return panel('My Results',`<div class="table-wrap"><table><thead><tr><th>Module</th><th>Score</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(S.courses.find(c=>c.id===r.courseId)?.title||r.courseId)}</td><td>${badge((r.score||0)+'%')}</td><td>${badge(r.passed?'Passed':'Needs Review')}</td></tr>`).join('')}</tbody></table></div>`)}
function wire(){document.querySelector('#courseForm')?.addEventListener('submit',createCourse);document.querySelectorAll('.quiz-form').forEach(f=>f.onsubmit=submitCheck)}
async function createCourse(e){e.preventDefault();await run(async()=>{let questions=[1,2,3].map(i=>({question:val('#q'+i),answer:norm(val('#a'+i))})).filter(x=>x.question&&x.answer);await addDoc(collection(db,'trainingCourses'),{title:val('#courseTitle'),content:val('#courseContent'),questions,status:'Active',createdByEmployeeId:S.emp.employeeId,createdBy:S.emp.employeeId,updatedByEmployeeId:S.emp.employeeId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await log('LEARNING_MODULE_CREATED',{title:val('#courseTitle')})},'Learning module created.')}
async function submitCheck(e){e.preventDefault();await run(async()=>{let course=S.courses.find(c=>c.id===e.target.dataset.course),qs=course.questions||[],correct=0;qs.forEach((q,i)=>{if(norm(e.target.querySelector(`[name=q${i}]`)?.value)===norm(q.answer))correct++});let score=qs.length?Math.round(correct/qs.length*100):100,passed=score>=70;await addDoc(collection(db,'trainingResults'),{courseId:course.id,employeeId:S.emp.employeeId,score,passed,correct,total:qs.length,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await log('LEARNING_CHECK_SUBMITTED',{courseId:course.id,score})},'Learning check submitted.')}
init();
